name: Build and release J2V8

on: workflow_dispatch

jobs:
  build_j2v8_android:
    name: Android
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set Up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build release .aar
      run: ./gradlew assembleRelease

    - name: Archive J2V8 Android aar
      uses: actions/upload-artifact@v1.0.0
      with:
        name: j2v8-android-aar
        path: build/outputs/aar/j2v8-release.aar
